#!/bin/bash
# Website Cloner 插件安装和测试指南

echo "🚀 Website Cloner 插件安装指南"
echo "================================"
echo ""

echo "📦 方法1：直接使用插件目录（推荐用于开发测试）"
echo "-------------------------------------------"
echo "在当前目录运行："
echo "  claude --plugin-dir ./website-cloner-plugin"
echo ""

echo "📦 方法2：添加本地市场"
echo "-------------------------------------------"
echo "1. 启动 Claude Code"
echo "2. 运行以下命令添加市场："
echo "   /plugin marketplace add $(pwd)/website-cloner-plugin"
echo ""
echo "3. 安装插件："
echo "   /plugin install website-cloner@website-cloner-marketplace"
echo ""

echo "📦 方法3：从 GitHub 安装（需要先推送到 GitHub）"
echo "-------------------------------------------"
echo "1. 将插件推送到 GitHub 仓库"
echo "2. 添加市场："
echo "   /plugin marketplace add your-username/website-cloner-plugin"
echo "3. 安装插件："
echo "   /plugin install website-cloner@your-username-website-cloner-plugin"
echo ""

echo "✅ 使用方法"
echo "-------------------------------------------"
echo "安装后，使用以下命令克隆网站："
echo "  /website-cloner:clone https://example.com"
echo ""

echo "🧪 快速测试"
echo "-------------------------------------------"
echo "测试克隆一个简单网站："
echo "  /website-cloner:clone https://example.com"
echo ""
echo "测试克隆一个复杂网站："
echo "  /website-cloner:clone https://www.anthropic.com"
echo ""

echo "📁 输出位置"
echo "-------------------------------------------"
echo "克隆的网站将保存在："
echo "  ./cloned-sites/<域名>/"
echo ""

echo "🌐 本地预览"
echo "-------------------------------------------"
echo "使用 Python 启动本地服务器："
echo "  cd cloned-sites/example.com"
echo "  python -m http.server 8000"
echo "  然后访问: http://localhost:8000"
echo ""

echo "✨ 完成！现在可以开始使用 Website Cloner 插件了！"
