#!/bin/bash
# Plugin Creator 安装和测试指南

echo "🚀 Plugin Creator 安装指南"
echo "================================"
echo ""

echo "📦 方法1：直接使用插件目录（推荐用于开发测试）"
echo "-------------------------------------------"
echo "在当前目录运行："
echo "  claude --plugin-dir ./plugin-creator-plugin"
echo ""

echo "📦 方法2：添加本地市场"
echo "-------------------------------------------"
echo "1. 启动 Claude Code"
echo "2. 运行以下命令添加市场："
echo "   /plugin marketplace add $(pwd)/plugin-creator-plugin"
echo ""
echo "3. 安装插件："
echo "   /plugin install plugin-creator@plugin-creator-marketplace"
echo ""

echo "📦 方法3：从 GitHub 安装（需要先推送到 GitHub）"
echo "-------------------------------------------"
echo "1. 将插件推送到 GitHub 仓库"
echo "2. 添加市场："
echo "   /plugin marketplace add your-username/plugin-creator-plugin"
echo "3. 安装插件："
echo "   /plugin install plugin-creator@your-username-plugin-creator-plugin"
echo ""

echo "✅ 使用方法"
echo "-------------------------------------------"
echo "安装后，使用以下命令创建新插件："
echo ""
echo "  # 基本创建"
echo "  /plugin-creator:create my-plugin"
echo ""
echo "  # 带描述创建"
echo "  /plugin-creator:create my-plugin \"插件描述\""
echo ""

echo "🧪 快速测试"
echo "-------------------------------------------"
echo "创建一个测试插件："
echo "  /plugin-creator:create test-plugin \"测试插件\""
echo ""
echo "测试生成的插件："
echo "  cd test-plugin-plugin"
echo "  ./validate.sh"
echo "  claude --plugin-dir ."
echo ""

echo "📁 生成的文件"
echo "-------------------------------------------"
echo "每个插件包含："
echo "  ✓ .claude-plugin/plugin.json"
echo "  ✓ .claude-plugin/marketplace.json"
echo "  ✓ commands/example.md"
echo "  ✓ skills/example/SKILL.md"
echo "  ✓ README.md"
echo "  ✓ USAGE_GUIDE.md"
echo "  ✓ QUICKSTART.md"
echo "  ✓ INSTALL.sh"
echo "  ✓ validate.sh"
echo "  ✓ .gitignore"
echo "  ✓ LICENSE"
echo "  ✓ PROJECT_STRUCTURE.md"
echo ""

echo "🔍 验证插件"
echo "-------------------------------------------"
echo "生成插件后，运行验证："
echo "  cd <plugin-name>-plugin"
echo "  ./validate.sh"
echo ""

echo "✨ 完成！现在可以开始使用 Plugin Creator 了！"
