#!/bin/bash
# Codex Plugin 安装和测试指南

echo "🚀 Codex Plugin 安装指南"
echo "================================"
echo ""

echo "📦 方法1：直接使用插件目录（推荐用于开发测试）"
echo "-------------------------------------------"
echo "在当前目录运行："
echo "  claude --plugin-dir ./codex-plugin"
echo ""

echo "📦 方法2：添加本地市场"
echo "-------------------------------------------"
echo "1. 启动 Claude Code"
echo "2. 运行以下命令添加市场："
echo "   /plugin marketplace add $(pwd)/codex-plugin"
echo ""
echo "3. 安装插件："
echo "   /plugin install codex@local-codex"
echo ""

echo "📦 方法3：从 GitHub 安装（需要先推送到 GitHub）"
echo "-------------------------------------------"
echo "1. 将插件推送到 GitHub 仓库"
echo "2. 添加市场："
echo "   /plugin marketplace add your-username/codex-plugin"
echo "3. 安装插件："
echo "   /plugin install codex@your-username-codex-plugin"
echo ""

echo "✅ 使用方法"
echo "-------------------------------------------"
echo "安装后，可以使用以下命令："
echo ""
echo "  # 快速代码审查"
echo "  /codex:quick-review"
echo "  /codex:quick-review security"
echo ""
echo "  # 执行 Codex 任务"
echo "  /codex:exec run all unit tests"
echo "  /codex:exec update API documentation"
echo ""
echo "  # 恢复会话"
echo "  /codex:resume"
echo "  /codex:resume last"
echo ""
echo "  # 应用更改"
echo "  /codex:apply"
echo ""

echo "🧪 快速测试"
echo "-------------------------------------------"
echo "测试快速审查："
echo "  /codex:quick-review"
echo ""
echo "测试任务执行："
echo "  /codex:exec echo 'Hello from Codex'"
echo ""

echo "📋 前置要求"
echo "-------------------------------------------"
echo "确保已安装："
echo "  - Claude Code 1.0.33 或更高版本"
echo "  - Codex CLI 工具"
echo "  - 有效的 Codex 认证"
echo ""
echo "检查 Codex 安装："
echo "  codex --version"
echo ""

echo "🔍 故障排除"
echo "-------------------------------------------"
echo "如果插件未加载："
echo "  1. 检查插件结构: ls -la codex-plugin/.claude-plugin/"
echo "  2. 验证配置文件: cat codex-plugin/.claude-plugin/plugin.json"
echo "  3. 重启 Claude Code"
echo ""
echo "如果 Codex 未找到："
echo "  1. 验证安装: codex --version"
echo "  2. 检查 PATH: which codex"
echo ""

echo "✨ 完成！现在可以开始使用 Codex Plugin 了！"
